---
- name: Smart Playbook
  hosts: test

  tasks:
  - name: Update apt cache and install Python 3
    apt:
      name: python3
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Stop firewall
    service:
      name: ufw
      state: stopped
      enabled: no
    when: ansible_distribution == "Ubuntu"

  - name: Update yum cache and install Python 3
    yum:
      name: python3
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Stop firewall
    service:
      name: firewalld
      state: stopped
      enabled: no
    when: ansible_distribution == "CentOS"

- name: File module and lineinfile module
  hosts: all

  tasks:

  - name: Include variables from 'config.yaml'
    include_vars:
      file: config.yaml

  - name: create a file called 'UpdateHelloWorld' in the '/' directory
    file: 
      path: '/UpdateHelloWorld'
      state: touch
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0755'

  - name: Copy 'myname' to the /home/vagrant directory
    copy: 
      src: myname 
      dest: "/home/{{ user }}/myname"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0755'

  - name: View content of 'myname'
    shell: "cat /home/{{ user }}/myname"
    register: output

  - name: Show output of 'myname'
    debug: 
      var: output

